### ISSUE TITLE
Dark Theme Reader Mode

### ISSUE THREAD

**Issue by winstonma** [plateaukao/einkbro#131]
I set my device into dark theme, opened [Demo Page Link](https://canucksarmy.com/2022/06/25/canucks-sign-kamloops-blazer-captain-former-lightning-draft-pick-quinn-schmiemann/) in EinkBro and then use reader mode. And this is the screenshot:

![Screenshot_20220626-203614776](https://user-images.githubusercontent.com/1215090/175814760-925850f0-55f7-45d0-8849-cc762c98fb43.jpg)

This is my phone, running crDroid 6 (Android 10) with dark theme enabled.

Is it possible that the reader mode comes with dark background? I am using some reader mode addon in chrome and this is their settings (just a reference):

- Background Color: #1A1A1A
- Text Color: #E0E0E0
- Link Color: #FFFFFF

**Comment by plateaukao** [comment]
it works on my OPPO device with Android 11. 
Maybe it's something wrong with your WebView. Did you update it to latest in Play Store? If not, please do so.

As for supporting separate theme for Reader Mode, I'll put it into TODO list. However, it's less Eink related feature, the priority would not be high.

![Screenshot_2022-06-27-13-22-45-26_5cd225ada6153df039aa0f4408fcc4ec](https://user-images.githubusercontent.com/4084738/175865678-20303adc-1356-4cf0-98b2-5810fa3382fd.jpg)

![Screenshot_2022-06-27-13-22-34-36_5cd225ada6153df039aa0f4408fcc4ec](https://user-images.githubusercontent.com/4084738/175865689-b8a608cb-ebc7-4fc0-81d4-7afbebc0cc99.jpg)

**Comment by winstonma** [comment]
The webview on my phone is version 103.0.5060.53. I also ran this on my Amazon Fire Tablet HD (running Android 8) and it has similar behavior.

Is it a good idea if I can obtain a debug mode of the app and I capture the log with the debug mode verion?

**Comment by winstonma** [comment]
Yes Dark Theme is not supported until Android 10. I am using Android 8 Tablet running LinageOS (new Cyanogenmod) which support theme (not actual dark theme) so my device is running dark theme.

My phone is running crDroid 6 (Android 10, screenshot at https://github.com/plateaukao/einkbro/issues/131#issue-1284904133) and it is running dark theme.

Would you consider [dark theme switch](https://proandroiddev.com/implementing-dark-theme-in-your-android-application-ec2b4fefb6e3) inside settings?

**Comment by winstonma** [comment]
I mentioned about Fire Tablet having Dark Theme.

On Fire Tablet I installed [Via browser]( https://play.google.com/store/apps/details?id=mark.via.gp) and I don't understand how they know the dark theme is running. But it just know my Android 8 is running Dark Theme.

I also switched back to Light Theme and see that Via Browser just go back to light theme.

**Comment by plateaukao** [comment]
(Web content) Dark mode setting is already added to Settings already. It's under Settings > Behavior/UI > Dark Mode. However, it only controls Web part. As for EinkBro UI, it follows system-wise setting.

Via browser is not open sourced, so I couldn't know how it's done that. If you could find more information about how to do so , I will take a look at it and see if I can adopt similar behavior. Before that, since this feature is not directly related to Eink devices, I may not spend time on it any time soon.

**Comment by winstonma** [comment]
Totally agree that Via Browser is playing some magic and no one knows how he got that. Other app that support dark theme won't work on old Tablet. I just want to let you know some app can read the theme color of old devices.

I didn't know that there is a force dark mode inside settings that's why I wrote down and see if I can get dark theme for my old tablet.

Thanks for pointing me to this.

**Comment by winstonma** [comment]
@plateaukao Sorry to interrupt again

I just tried to force the app in Dark Theme but this settings only available in Android 10+ device. Would it be possible to add the Dark Theme settings for old devices?

**Comment by plateaukao** [comment]
@winstonma  
Originally, the setting is fixed, even under Android 10 users can see it. However, sometimes users complain that the dark mode does not work. After checking, it's due to their Android OS is not new enough. So, I added constraints to it: only Android 10+ will show that setting.

Since using custom ROMs is not common, and it also does not guarantee it works for ported ported dark mode for OS under Android 10, I would like to keep current implemenetation.

If you really want it for your own usage, you can change [this line](https://github.com/plateaukao/einkbro/blob/852384ad2e75658e6791f3366df719380479e1a1/app/src/main/java/de/baumann/browser/fragment/UiSettingsFragment.kt#L28) to 
```
findPreference<ListPreference>("sp_dark_mode")?.isVisible = true
```

and build the apk locally.

**Comment by winstonma** [comment]
I didn't ask you to cater the custom rom by any means. I just wonder if it is possible that the Dark Theme is supported even for old device.

I totally understand that custom rom is not common and I am not asking you to cater the custom rom. But also at the same time I am not sure the Dark Reader Mode is caused by the custom rom. Therefore I would be happy to assist on finding the root cause of the problem. (https://github.com/plateaukao/einkbro/issues/131#issuecomment-1166894064)

**Comment by winstonma** [comment]
I see. Currently I don't have an envoirnment that can turn source code to apk. I may setup one.

**Comment by plateaukao** [comment]
You could try this version (https://github.com/plateaukao/einkbro/releases/tag/v8.31.0) in which Dark mode is still visible in Settings > Behavior/UI screen.

**Comment by winstonma** [comment]
@plateaukao Just installed version v8.31.0 onto my Android 8 tablet. It doesn't work.

I guess the only way to make this work is to more or less like [Pocket](https://play.google.com/store/apps/details?id=com.ideashower.readitlater.pro) - extract the content and then theme the content (like epub reader).
