### ISSUE TITLE
YouTube Kids website not loading correctly 

### ISSUE THREAD

**Issue by Kita2345** [plateaukao/einkbro#154]
YouTube Kids (https://www.youtubekids.com/) does not load correctly - as a mobile website - in einkbro. Instead of loading the contents, it forwards you to the download page for the YouTube Kids apps (https://www.youtube.com/kids).

**Comment by plateaukao** [comment]
It's redirected by Youtube website. It's also redirected on Firefox app too. So, I think youtube web service should do the chane instead.

**Comment by Kita2345** [comment]
Worked fine with DuckDuckGo

**Comment by plateaukao** [comment]
Since the redirection is done by Youtube site, without knowing its logic, it's hard to do anything from browser side. Also, I saw you post this issue to several browsers too. So, I think it's Youtube site who should fix this, instead of asking browsers to have workaround for it.

![image](https://user-images.githubusercontent.com/4084738/189541524-fa20bf79-c1dc-4a52-ac8a-6ac8971596ad.png)
