### ISSUE TITLE
Enhance translate feature.

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#172]
ver 9.8.0
Note Air 2
settings: Behavior/UI > Save tabs [ON] (everything else is OFF)

-, Is it possible to add translate feature to select pop-up? I mean "Translate" to "Copy|Share|Select all|Web Search|Eink bro" pop up.

Translate text can be either returned as
--, pop-up
--, or in place of original selected text 
what ever is easier.

Use cases:
--, blog post in Spanish which has comments in Portuguese
--, popular youtube video which has comments in Spanish, Chinese, Arabic, etc..

---
-, Also I played with current translate functionality, and it's very useful. I think "Google in place" is most convenient, then "Google full page", "Google text" is least usefull. However first 2 work not on all pages, could you please explain why? 

Example:
--, "Google in place" does not work with Zhihu (works with "Google full page") https://www.zhihu.com/question/552287294
--, "Google in place" and "Google full page" do not work with Twitter https://mobile.twitter.com/BlackJunkDog/status/1572701756790042624

**Comment by plateaukao** [comment]
1. for partial selection translate feature, please install other specific dictionary apps like Google Translate, 歐陸詞典 or mdict. They did what you need already, and provide better flexibility.
2. The reason why Google Text could only be done by pages is because of the limitation of Google service. It only allows around 500 characters per time for translation. For unlimited translation, I have to call paid API, which I don't bother to.
3. For some websites, the translation not working is because these websites have more restricted security rules that they don't allow any javascript injections. I have no way to surpass this. In these scenarios, if you still need web translate, you could use chrome instead.
4. Google full page translate, it just pass the website url to Google Translate web, so it does not work with somehting that needs login first.

**Comment by gety9** [comment]
@plateaukao

thank you for explanation

"for partial selection translate feature, please install other specific dictionary apps like Google Translate, 歐陸詞典 or mdict. They did what you need already, and provide better flexibility."

-, worked great, thank you!
