### ISSUE TITLE
shouldn't the latest version be 9.9.1? 

### ISSUE THREAD

**Issue by thotsputin** [plateaukao/einkbro#178]
currently latest version (released an hour ago) says 9.10.0. isn't that like, backwards?

just sayin

**Comment by plateaukao** [comment]
@thotsputin 

The version naming convention is major.minor.hotfix
major number increases when there's big features or something incompatible changes with previous version.
minor number increases when having new features.
hotfix number is used when something critical went wrong with normal release, and need to fix asap without adding new features.

So, for this release, it's normal release with new features; that's why it goes from 9.9 to 9.10
