### ISSUE TITLE
Increase menu items and text

### ISSUE THREAD

**Issue by hooddy** [plateaukao/einkbro#189]
![photo_2022-12-07_09-00-23](https://user-images.githubusercontent.com/6899176/206100523-bc57dc3a-9940-4027-bcd5-850ab63bdd01.jpg)
Please made menu items (maybe) and text (for sure) scaled to screen. It's hard to read items description. Icons is ok but text its hard to read.

**Comment by plateaukao** [comment]
Hi, @hooddy 
May I know what device are you using, and its screen size? 
Also, you could enlarge the system font so that the text would be larger.
Since this browser is mainly designed for Eink devices, I would like to reduce screen re-paint as much as possible. So, if the icons are clear enough and large enough to be accessed, the text is only for supplementary.

If you really want a version that comes with bigger icon text size, you could modify it yourself, and build your own version.

**Comment by hooddy** [comment]
@plateaukao im using Hisense A5 proCC e-ink (for sure) phone. specs is like thise one https://www.devicespecifications.com/en/model/2ebd5387
I don't like increasing system font coz its okay to me. but did ya mean that description under icons is depends on it? its frustrate me a lil. maybe its fine to use normal (not bold) font for it? or make a lil bigger... its hard to understand did it use font smoothing or not.

**Comment by plateaukao** [comment]
@hooddy I happen to have A5pro CC too. I’m not aware that the text under icons are using bold font. If so, I’ll modify it back to normal type then.

**Comment by plateaukao** [comment]
Also, it may be because of the nature of color Eink screen; due to color support, it’s now as clear as other Black&White only Eink devices.

**Comment by plateaukao** [comment]
@hooddy 
I checked the built-in browser. Its menu font is almost the same size as EinkBro. I think it's normal to have small font size on such a tiny phone.

![Screenshot_20221208_232327](https://user-images.githubusercontent.com/4084738/206485349-4d554d87-a189-42fa-9802-8652a3f654b3.png)
