### ISSUE TITLE
"Copy" URL on Mastodon pages do not seem to copy the text

### ISSUE THREAD

**Issue by ziggyb1013** [plateaukao/einkbro#190]
1. Go to a Mastodon user's page (without logging in to a Mastodon account if you have one): https://mastodon.social/@nocontexttrek
2. Click on the "Follow" button
3. It will bring up a dialog box that will have you "Copy" the user's URL in order to follow that user on your own instance. (Yes, it's a convoluted way to follow a user, not on your server/instance)

- The copy button doesn't seem to actually copy the URL.
- Manually selecting the URL and copying does work as expected.

Off topic: Do you have a Mastodon account?

**Comment by plateaukao** [comment]
@ziggyb1013  
I think this issue is the same as the copy button issue in Github. Android's WebView does not support some web features (e.g., copy through `navigator.clipboard.writeText()`). 

ref: https://stackoverflow.com/a/61546346/1265915

No, I haven't created Mastodon account yet, although I already downloaded it on my phone. :D

**Comment by ziggyb1013** [comment]
Oh weird omission on Android. 

Well if you do join mastodon, please announce. I've stopped using Twitter due to all the drama over its new policies.
