### ISSUE TITLE
Extra spacing after an apostrophe

### ISSUE THREAD

**Issue by charleshan** [plateaukao/einkbro#192]
**What device and app version are you using**
 - Device: Onyx Poke 3
 - OS: Android 10
 - Browser: EInkBro
 - Version: 9.15.0
 - Android System WebView Version: 108.0.5359.79

**Describe the bug**
There's an extra space added to the content after an apostrophe.

**To Reproduce**
1. Visit https://www.lennysnewsletter.com/p/what-theyd-do-differently-kickstarting on EInkBro.
2. Go to 7. Do things that don't scale longer

**Expected behavior**
I would expect there isn't an extra spacing after an apostrophe for content displayed.

**Screenshots**
![20221215_000614537](https://user-images.githubusercontent.com/3143154/207742074-14e8d51a-2387-497a-a103-a9d332355f9b.jpg)

**Comment by charleshan** [comment]
Might be related to https://github.com/wordpress-mobile/WordPress-Android/issues/15522

**Comment by plateaukao** [comment]
@charleshan 
I think it's an issue of the article, not related to WebView or EinkBro App.
And the reason is because that `'` is a fullwidth character, instead of a normal halfwidth character. That's why it takes more spaces. If you try to do text selection, you can notice that there isn't space between `'` and `t`. 
Also, you can see that in other places in the article, all the other `'` behave well.
In addition, if you read the article inside system built-in Neo Browser, it has the same problem.

I believe that it's caused by error inputting fullwidth character, and for BOOX, its built-in font uses extra size to display the `'` for fullwidth characters.

**Comment by charleshan** [comment]
Thanks for the explanation. I think you made a typo and mixed up `’` with `'` but I got your point.

I'll close this issue since it's something BOOX needs to fix. If anyone else comes across this issue and has BOOX device, please submit a feedback to the BOOX team in Settings > Feedback > plus icon :)

**Comment by dredmorbius** [comment]
I can confirm that this is a 3.2 Onyx BOOX firmware issue.

I've encountered the same issue, noted here on Reddit:  <https://old.reddit.com/r/Onyx_Boox/comments/zl722g/web_content_glitch_large_space_after_all/>

(There are several other reports, noted in my own.)

I've heard from Onyx that they're aware and will fix.
