### ISSUE TITLE
Many github pages strobe on Eink-browser

### ISSUE THREAD

**Issue by softvision-raul-bucata** [plateaukao/einkbro#220]
**URL**: https://github.com/tmmcguire/Fletcher_Pratt_NWG

**Browser / Version**: EinkBro v9.20.0
**Operating System**: Android 8.1.0
**Tested Another Browser**: Yes Firefox

**Problem type**: Something else
**Description**: Many github pages strobe on eink-browser
**Steps to Reproduce**:
On Eink-Browser, there is repeated fast, blinding, painful flashing. I think it is in the area with the user name, left of the number of commits.

**Notes:**
Originally reported here: https://github.com/webcompat/web-bugs/issues/118519

**Comment by softvision-raul-bucata** [comment]
This is a report coming from webcompat.com. As it seems to be an accessibility issue, and we do not have any contacts at Eink Browser, we saw fit to report it here.

**Comment by plateaukao** [comment]
@MarjaE2

please give information about which device you tested with, and which refresh mode you are using. 

I could not reproduce this issue on my devices either.

**Comment by plateaukao** [comment]
@MarjaE2 
I tried the github url on my Likebook-T80D, and its Android version is also 8.1.0 too.
I could see the flashing you mentioned too. 
However, I guess it's because of the old version of WebView.
If I try more times to reload the page, sometimes it could be successful loading the text response, so that the icon and author name does not flash anymore; however, most of the time I guess the http request failed to fetch the author name; that's why it keeps flashing(loading) and waiting for response.

**The same issue happens on built-in browser in Likebook-T80D too.**
I tried install chrome on it, and it works well. So I would suggest using Chrome in these scenarios.
In Android 8.x, it uses Chrome's WebView as system WebView solution. So, if you install latest Chrome, maybe the symptom in EinkBro would be gone. You could try this too.
If not, since the root cause is not within EinkBro app's logic, I could not do anything about it.
