### ISSUE TITLE
can we have a version supporting android 4.0.4?

### ISSUE THREAD

**Issue by bibu2651** [plateaukao/einkbro#228]
The app is awsome, I installed it to all my everyday eink devices, except an old 13.3' one, which still running android 4.0.4. Is it possible to support for older system? Thanks.

**Comment by plateaukao** [comment]
@bibu2651 
Glad to hear that it's useful for your eink devices.
For devices with Android 4.x, it's hard to support, because Android 4.x was released more than 10 years ago, most of the implementations were different and can't be used anymore. It's kind of asking me writing a whole new implementation for it, and need to maintain it separately.

I tried, but failed. It may be faster to ask other Open Source browsers that still supports Android 4.x to add some eink features for you. :)

**Comment by bibu2651** [comment]
thanks a lot
