### ISSUE TITLE
Request Do Not Track and Data saver

### ISSUE THREAD

**Issue by lawson85** [plateaukao/einkbro#249]
These would enticed people who are privacy concerned or on a limited data plan. 

Some info here: https://requestly.io/blog/http-headers-that-every-web-developer-should-know

https://whoer.net/blog/do-not-track-dnte/

https://www.geeksforgeeks.org/http-headers-save-data/

**Comment by goblin535353** [comment]
> Thank you for the suggestion. I'll take into consideration in future versions.

I just discovered this browser and so far am impressed. I would apprecciate more privacy focused options if possible :)

**Comment by Kinue72** [comment]
The 'Do Not Track' header can be used to fingerprint you. More info: https://getinsights.io/blog/posts/fingerprinting-do-not-track

**Comment by andrew-aitchison** [comment]
GPC https://globalprivacycontrol.org/ seems to be taking over from do not track. It appears to be legally binding in eg EU and California.

**Comment by andrew-aitchison** [comment]
FOSSbrowser supports GPC, which will help if the code has not diverged too much.

**Comment by plateaukao** [comment]
pull request is welcomed.

**Comment by Kita2345** [comment]
https://gitlab.com/TipzTeam/viola

Pada Sab, 16 Des 2023 11.18, Daniel Kao ***@***.***> menulis:

**Comment by Kita2345** [comment]
https://github.com/LNReader/lnreader

Pada Jum, 12 Apr 2024 00.09, Kiri gaya ***@***.***> menulis:

**Comment by Kita2345** [comment]
Hai,

Improve desktop mode

go to stackoverflow
change to desktop site
ensure site loads desktop site instead of mobile site


https://web.autocad.com/ produces unsupported browser error on load

Describe the bug
https://web.autocad.com/ will present a "unsupported browser" error

To Reproduce
Steps to reproduce the behavior:
Open https://web.autocad.com/ on desktop mode
Wait a few seconds, and it'll redirect too
https://web.autocad.com/unsupported-browser

Expected behavior
Load webpage without error

**Comment by Kita2345** [comment]
Hai,

improvement and feature like

 https://hermit.chimbori.com/features/

https://play.google.com/store/apps/details?id=com.chimbori.hermitcrab

**Comment by Kita2345** [comment]
System info: 11(30), OPPO, OP4EFDL1(CPH2127), CPH2127_11_C.23,
Asia/Jakarta, id


 Improve desktop mode

go to stackoverflow
change to desktop site
ensure site loads desktop site instead of mobile site


https://web.autocad.com/ produces unsupported browser error on load

Describe the bug
https://web.autocad.com/ will present a "unsupported browser" error

To Reproduce
Steps to reproduce the behavior:
Open https://web.autocad.com/ on desktop mode
Wait a few seconds, and it'll redirect too https://web.autocad
.com/unsupported-browser

Expected behavior
Load webpage without error
