### ISSUE TITLE
Disable cookies and the whitelist

### ISSUE THREAD

**Issue by islam2hamy** [plateaukao/einkbro#25]
Disable cookies
Add a site to the cookie whitelist (e.x : github.com)
Close the browser
Open it again and login to the site in the whitelist and using it for awhill , keep the tab , close the browesr , open the browser , using the site , close the site , re open the site .
Keep going like that for a while

It doesn't work properly

**Comment by plateaukao** [comment]
Hi, I thought I already removed the cookie white list features. Did you add them from settings? Since it's advanced feature implemented before I started developping this browser, I inteneded not to support it anymore.  (maybe I should remove it from settings too). If you prefer a browser with flexible whitlist features, you could try the original FOSS browser. I believe the feature works in FOSS browser.

**Comment by islam2hamy** [comment]
Yes , from the settings
