### ISSUE TITLE
(UX) Option to disable bookmark priority from new tab url input view.

### ISSUE THREAD

**Issue by gety9** [plateaukao/einkbro#320]
- Device: Boox Note Air 2
 - OS: Android 11
 - EinkBro Version 11.0.0

Now most of the space of new tab url input view is occupied by bookmarks (example here first 14 lines, on mobile it's even worse - 28 lines)
![edit_20240110123801](https://github.com/plateaukao/einkbro/assets/16415882/953a9ba6-0b03-40b3-8fa1-bc90a7d7da4b)

in my opinion it's not UX friendly cause 1) if user looking for bookmarks we already have bookmarks view which user will prefer cause there each bookmark is in fixed place (which his muscle memory remembers), 2)it obstracts (you need to scroll up) recently visited pages, which i think user is likely to select / look for in the first place.

Simply recently visited pages sorted as time of visit (and firltered/searched by url input) is most UX friently view. 
And if user needs bookmarks he can always go to bookmark view.

**Steps**
1, press "+" (new tab) icon
2, observe bookmarks have priority weighting in output

**Comment by plateaukao** [comment]
will think about it. Thanks for the suggestion.

**Comment by gety9** [comment]
@plateaukao Daniel, thank you for consideration and listening to user feedback. Over the years Eink Bro became amazing browser thanks to amazing maintaner :) !!!

**Comment by dredmorbius** [comment]
@plateaukao Gah!  I was wondering what had happened to my bookmarks.  As of v11.3.1 (01281722), I'd noticed that when I enter a URL bookmarks aren't shown, which I very much do _not_ like.

I'd found that having bookmarks available and progressively filtering down as I entered a partial URL (often only 3--4 characters) made for much faster navigating to a page.  Yes, I can go through the bookmarks menu directly, but I have a lot of bookmarks in a lot of folders and that's **much** slower to navigate to a page than the partial-text-entry-then-tap-to-select option.

I just spent a few minutes looking for an option to have bookmarks visible on URL input.  I'd prefer either the former behaviour be restored or (sorry) an option be provided to enable/disable that behaviour.

As for recently-visited pages:  I disable history entirely so that isn't populated or useful to me.  User behaviour and preferences vary ...

**Comment by plateaukao** [comment]
@dredmorbius 
I see. Looks like this usage is used by some users. I'll add an option to show bookmarks in settings in next version.

**Comment by dredmorbius** [comment]
@plateaukao Thanks so much!

**Comment by dredmorbius** [comment]
@plateaukao Just a further thought:  providing matching entries from bookmarks (and browser history) is also how most other browsers (Firefox, Chrome, Safari, etc.) function presently, and have for years.  So on that basis that would be the standard and accepted behavour.

I'm aware you're already restoring the feature, but just wanted to provide a further justification.

**Comment by plateaukao** [comment]
@dredmorbius 
Actually, I don't care that much how other browsers work and what the norm is. I only code what I want, and along the way, I might adopt some behavior form other browsers that fits my needs and usage.
What you named are all browsers made by many developers, and they are meant for fitting average usage of every users. What are common behaviors on these browsers may not fit in EinkBro (or my personal needs).

Since EinkBro is lightweight browser, and most (Eink device) users use it for browsing common websites, I don't expect them to have many saved bookmarks (As least I don't have many). So, I think history search should be more useful than searching bookmarks that can easily accessed by 1 or 2 finger touches. It's much faster than typing words in input bar to search a specific bookmark (for most users).

Still I added an option (but default is off) in settings so that people can still see bookmarks if they really need it as before. 
fc2d8a69

**Comment by gety9** [comment]
@plateaukao Daniel, thanks for adding option to disable bookmarks, now history search is so much better!

**Comment by gety9** [comment]
I guess this can be closed now? Or do you want to keep it open?

**Comment by dredmorbius** [comment]
@plateaukao Apologies for the slow follow-up, but your response was pretty disappointing.

I'm not much of a fan of mainstream browsers myself.  That said, it's generally for the user-hostile, advertiser-friendly, and surveillance-oriented factors.  As well as, of course, lack of suitability to e-ink devices.  The ability to rapidly call up sites _of specific indicated interest to me_ is a case where both Chrome and Firefox actually serve my interests well.

I've had the opportunity to dig into my own EinkBro configurations over the past few days.  And I'd like to introduce you to the person who has ~500 bookmarks, organised by category, and used heavily.  That is, me.

What bookmarking provides over history-based recall is:

- I'm not polluting my search space with sites I happened to have visited, or actively wish to _avoid_ visiting, but happen to be in my history.
- I have a set of curated bookmarks **which I've added, named, and categorised myself** which I can call up.
- In most cases typing out 2--4 characters from the name or description is sufficient to bring up the relevant entry/ies.  E.g., "yco" for Hacker News, "nyt" for New York Times, etc.  That is, it's actually remarkably _little_ typing.
- You may not recall from earlier discussions, but I actively _disable_ history functions.  I'd rather not have that information on my device.  Though, and yes I'm aware of the incongruity, I prefer my tabs remain even between session restarts.

The alternative to typing a few characters is having to navigate through my bookmarks menus, which is more work and more tedious.  (I'll do that occasionally, but prefer text-based input generally.)

For this and some other reasons (badly broken scroll in the v11.4 release) I've rightgraded to v11.2.0, which behaves as I'd prefer.

**Comment by plateaukao** [comment]
@dredmorbius 
Now bookmarks can be displayed for input filtering if it's enabled in Settings > Behavior > Show Bookmarks when inpuing url. It should behave as old versions.
As for badly borken scroll in v11.4, I am not aware of the issue. As far as I use v11.6.0 now, everything works normally in my devices.

And for the usage of bookmarks, history, everyone has their own taste and preferred behavior. I'll try to fulfill my personal usage first, and then if I have time, I'll try to enhance it so that it may be more useful for more users. If I don't have time or I have no willing to do it, since EinkBro is open source, everyone can modify it to fit their needs. :)
