### ISSUE TITLE
Question about webview

### ISSUE THREAD

**Issue by heberjeur** [plateaukao/einkbro#332]
Hi, I want to know if any sensitive data can be transmitted to Google via WebView. Also, are browsers based on Firefox Geckoview more secure because they don't use WebView?

**Comment by plateaukao** [comment]
@heberjeur 
As far as I know, there's no sensitive data being transmitted to Google when using WebView. It's like using Android phone platform: normally, no sensitive data is not sent to Google. However, if the website you are visiting is integrated with Google Analytics library, or the app you are using is developed with other Google Tracking libraries, your behavior may be tracked, and action data may be sent to Google.

For your information, EinkBro does not integrate any tracking libraries. (On the bad side, if there's a lot of app crashes in certain releases, I don't know unless someone told me here.)

As for Firefox Geckoview, I haven't tried it so I don't know if it's safer. I'm not a security expert to give comments on this aspect. What I do know is: WebView is pre-installed and constantly updated on Android phone; that's the reason why EinkBro can be so small (less than 5MB). If an App is going to integrate with Firefox GeckoView, the app size would be several tens MB, since it needs to bundle GeckoView in it.
