### ISSUE TITLE
On URL entry, omit adding a space after a dot.

### ISSUE THREAD

**Issue by artelse** [plateaukao/einkbro#356]
When a URL is typed in the search field, a space is added automatically after typing the dot of a domain name. Other browser with the same keyboard does this correctly. Is there a keyboard mode that needs to be set perhaps?
Thanks!

**Comment by plateaukao** [comment]
I think it's the feature of your keyboard. it treats dot as end of senstence, and add space for you.you have to turn it off in your keyboard setting.

**Comment by artelse** [comment]
That's what I thought as well, but as said, my other browser doesn't have that problem. So I thought the browser can request a certain keyboard mode?

**Comment by plateaukao** [comment]
I tried. But before changing keyboard mode, it won't auto adding space on my other older android devices (android 11, etc) with Gboard input method.
And on my Pixel8 pro, the same EinkBro version, it will auto insert space after punctuation.
The reason why other browsers (Chrome, Edge, etc) does not have this issue may be because they are not written in Jetpack Compose. That's what I can think of.

**Comment by artelse** [comment]
Ok, thanks for the investigation! I now simply switched it off in Fleksy keyboard. You might close the issue now :)
