### ISSUE TITLE
einkbro no longer on Google Play store

### ISSUE THREAD

**Issue by uqs** [plateaukao/einkbro#357]
After reading the events in https://medium.com/einkbro/einkbro-app-%E8%A2%AB-google-play-store-suspend-2022f827081d I'd like to ask you to reconsider getting einkbro listed on the Play store again.

I didn't even notice for weeks that I wasn't getting any updates, as that's something I never check, and Play store or Fdroid just take care of these things for 99.9% of the users. I'm sure the majority of users wouldn't know how to sideload the APK or their device policy is forbidding this outright anyway.

To have an easier time sideloading the latest dev apk, you could either look into beta or alpha channels on the Play store to push out daily builds there, or it should be trivial to script a 1-button app (a background cronjob?), that checks for a newer github release and sideloads the app for developers, like you.

But I think the self-update mechanism is indeed not needed, and, well, it's against the terms of service. :/

Would you please consider:
- removing the self-update mechanism and using a helper script or alpha/beta channels for faster updates
- adding it back to the play store (maybe it's possible to reuse the name or id?)

**Comment by plateaukao** [comment]
I don't wanna follow google play store policies (lots of tedious work and guidelines) anymore on an open source project. If I happen to violate again, I'll get bad score on my google developer account. As a non profit app that I need to spend my free time on it, releasing it to google play store and taking care of all the rules and policies is no longer what I want to do. 

I develop this app mainly for my own use; so, if github sideloading way is not friendly enough to some potential users, they could still try fdroid. If not, maybe einkbro is not suitable for them. 

By the way, since einkbro is constantly adding new features, and unstable, in fact, there's no need to keep updating it if you find installed version is working good enough.

ps. it's not possibile to use the same app id. as for app name, I'm not sure. Anyways, I don't have intention to do so again. Life is short, I should spend time on something more valuable to myself.

**Comment by dredmorbius** [comment]
@plateaukao Are you still updating the F-Droid repo?

Most recent version there as I write is 11.4.0, while the most recent GitHub release is 11.6.0.

FYI, I'd tried downloading and installing the release zipfile with no joy relative to #320 and #358.  I ended up reverting to 11.2.0 via F-Droid.

Also:  providing an English-language translation of your Medium post would also be useful.

**Comment by plateaukao** [comment]
@dredmorbius 
The most recent version on fdroid is v11.6.0.
https://f-droid.org/en/packages/info.plateaukao.einkbro/
<img width="938" alt="image" src="https://github.com/plateaukao/einkbro/assets/4084738/f93adeaf-3e04-4e51-8288-1c0a6298763f">

As for the article, I don't have intention to explain to all the users in English. If someone really care about what happens, they can easily use Chrome translation or other translation website to read the article in English. :)

**Comment by dredmorbius** [comment]
@plateaukao Indeed it is as I check it now.  I was only seeing v11.4 as of my earlier comment.

But the key information is that you're still updating F-Droid, which I appreciate.

**On translation:**  English _is_ the most commonly-used 2nd language in the world.  And to be as clear as I can be:  I hugely appreciate Einkbro, find it far more than a "lightweight" browser (in terms of utility, rather than system load), and it ranks with Termux as the two most useful applications on my BOOX tablet.  I'm long familiar with Free Software (into my fourth decade of use), and the position and pressures of maintainers.  I'd be delighted for you to see support and reward for Einkbro (and have suggested as much to Onyx).  I'd really just like for it to be the best tool it can be.

As for translation:  the results I got through DeepL were serviceable, and as a low-cost approach, you might include that text with your Taiwanese Mandarin original.

<https://www.deepl.com/translator>

Since I don't usually say it, this is heartfelt:  thanks.

**Comment by uqs** [comment]
Turns out, I can still work around my device' policy by using `adb install` directly, so that fixes it for me.

One question though, I wasn't able to upgrade/reinstall, as it was complaining about different signatures. How does that work? I assume that you signed the Play store release with the same developer key as the Github release, is that not the case?

**Comment by plateaukao** [comment]
@uqs no, in recent days, developer don't sign apps on play store directly, they sign woth upload key, and play store will sign again, when repackaging apk corresponding to different screen sizes. so the signing key is different tham the one on github.

**Comment by jendraljack** [comment]
> @dredmorbius The most recent version on fdroid is v11.6.0. https://f-droid.org/en/packages/info.plateaukao.einkbro/ <img alt="image" width="938" src="https://private-user-images.githubusercontent.com/4084738/314126628-f93adeaf-3e04-4e51-8288-1c0a6298763f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5ODUzMTYsIm5iZiI6MTcxODk4NTAxNiwicGF0aCI6Ii80MDg0NzM4LzMxNDEyNjYyOC1mOTNhZGVhZi0zZTA0LTRlNTEtODI4OC0xYzBhNjI5ODc2M2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjFUMTU1MDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjExMDY5OThmNjg2MGZkMDg5ZDI2NjAwMzQ4NzA5ZjZhMWZjMjk3MGY5YWJjM2Q2ZDk2NzUyODE3OWM0NTU3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xqdzevP--ztyVIs7VDN04bMqw9dgtk3I5UTYbE3xqWA">
> 
> As for the article, I don't have intention to explain to all the users in English. If someone really care about what happens, they can easily use Chrome translation or other translation website to read the article in English. :)

i like several feature,
But if open new tab, that not add new tab and close previous tab. Mean app can not  open new tab from link from webpage when open.
