### ISSUE TITLE
FR: Implement "Bypass Paywall"

### ISSUE THREAD

**Issue by unacceptablet** [plateaukao/einkbro#378]
1. I know Einkbro does not and will not support extensions / plug-ins. But is there any way to integrate "Bypass Paywall Clean" ?
https://github.com/bpc-clone/bypass-paywalls-chrome-clean

2. Alternatively, we can tap on the edit URL > select  a word > select all to copy full URL > open another tab > type archive.ph and enter > paste the URL > click save > bypass robot check to get the full article. Which is a lot of work. Is there any shortcut where if I long tap on an article, it will automatically take me to the bypassed page on archive.ph or at least close to it? (example site: www.economist.com)

**Comment by plateaukao** [comment]
it seems that the chrome extension on github no longer provide editable source codes.

**Comment by plateaukao** [comment]
@unacceptablet 
Thanks for providing alternative source code links. I'll look into them.
the first one does not contain codes either, but the second one does.
However, the chances that I integrate them into EinkBro is not high though.

As for your second suggestion to `if I long tap on an article, it will automatically take me to the bypassed page on archive.ph or at least close to it?`, you may need to modify the codes to support similar behavior. I could point out where you could start to modify in the codes, but I myself would not implement this, since it's not a feature I need in near future; and ... I do suggest paying to read these articles. :)
