### ISSUE TITLE
App switching behaviour & other problems

### ISSUE THREAD

**Issue by unacceptablet** [plateaukao/einkbro#387]
1. When I switch from Koreader to einkbro, it creates a new tab. Is there anyway to not do that? (I dont have the same problem when using the task switcher but using task switcher is a hassle in boox). 

https://github.com/user-attachments/assets/71fa853f-a88a-467e-986e-68cac9516297

 2. Is there any way to disable the sign-in with google prompt in eInkbro?

![remove google](https://github.com/user-attachments/assets/3a02ed06-4243-4f96-aa8c-775d583f6e78)

3. Is there any way to find why eInkbro keeps crasing when using a pop up window?

https://github.com/user-attachments/assets/25a63700-8716-40d0-93de-bb86f2538c92

4. Is there anyway I can quickly swtich betwee apps by double tapping task switcher button twice like we do in android? (I know this is not your area but let me know if you know any tricks.)

**Comment by plateaukao** [comment]
@unacceptablet 
next time, please separate issues into different issues.

>When I switch from Koreader to einkbro, it creates a new tab. Is there anyway to not do that? (I dont have the same problem when using the task switcher but using task switcher is a hassle in boox).

It's fixed in snapshot version. You can install snapshot version or wait for next release.
https://github.com/plateaukao/einkbro/issues/384

> Is there any way to disable the sign-in with google prompt in eInkbro?

No. It's specific website behavior. I do not handle it now and probably won't do so in future. You can modify the app if you know how to code.

> Is there any way to find why eInkbro keeps crasing when using a pop up window?

use issue template to provide all necessary information.
from your video, I suspect that it's due to low memory on your device when you launch dictTango, and your device system will automatically close any app in background. It's system issue. Try use a more powerful device, or any device with more available RAM.

> Is there anyway I can quickly swtich betwee apps by double tapping task switcher button twice like we do in android? (I know this is not your area but let me know if you know any tricks.)

use issue template to provide all necessary information.
I don't know what device you're using. Usually it's implemented by manufacturer. If it's not working for your device, ask the device vendor to support it.
