### ISSUE TITLE
Boox Palma Incorrect Language

### ISSUE THREAD

**Issue by mcrosson** [plateaukao/einkbro#400]
**What device and app version are you using**
 - Device: Boox Palma
 - OS: Android 11
 - EinkBro Version v11.15.0 (github release)

**Describe the bug**
The browser language used to be english and now is mostly not english (I cant tell if it's chinese, korean, japanese or similar) and the ui is impossible to use for me (I only speak/read english) as nearly all of the ui controls are labelled in another language.

**To Reproduce**
Install v11.15.0 from github on a boox palma with the language set to 'english (united states)'

**Expected behavior**
The ui to be presented in english when the android system is set to 'english (united states)'

**Screenshots**
![Screenshot_20240905-183312](https://github.com/user-attachments/assets/4535c938-9f70-4168-8ab7-5e3228855b48)
![Screenshot_20240905-183323](https://github.com/user-attachments/assets/9f0ad092-4e0c-432d-abb7-98e1967705f9)
![Screenshot_20240905-183338](https://github.com/user-attachments/assets/deadaed1-fb38-447d-9a91-a13f04b75c06)

**Comment by plateaukao** [comment]
I added a feature to change app langueage in EinkBro: you can go to Settings > UI (first item), and scroll to last item, to choose English, before this issue is fixed.

Originally, if you do not set up the languge in EinkBro, it should use the system setting, I don't know why it's not working on Palma. I'll check out why.
