### ISSUE TITLE
Problems with video playback in recent versions

### ISSUE THREAD

**Issue by chwt163** [plateaukao/einkbro#422]
Please write necessary information as described below. If information is not enough, I may not have time to look into it.

**What device and app version are you using**

 - Device: OPPO PJU110(PJU110)
 - OS: ColorOS14.0
 - EinkBro Version [e.g. 11.17.0~12.1.0 ]

**Describe the bug**

https://tv.cctv.com/live/cctv13/
V11.14.0： The website video can be played normally
V11.17.0~12.1.0：Play the site's video, and every few seconds there will be a pause to come back.

**To Reproduce**
Play the site's video, and every few seconds there will be a pause to come back.

** What's the behavior on following similar browsers **
* Via Browser No problem

**Comment by chwt163** [comment]
I tested it with another mobile phone just now, and it was also V12.0 that didn't work, and V11.4 had no problem

Device: HONOR BKL-AL20(BKL-AL20)
Android Version: 10 API29
WebView Version: 118.0.5993.80(599308001)

**Comment by plateaukao** [comment]
@chwt163 
Thank you for reporting this issue. After investigation, it's caused by new feautre (load web by cache by default).
You can turn off the feature in Settings > Behavior > Enable Web Cache; and then restart the app.

I'll make this option to be false by default, so that it won't cause other issues. And users can turn on it on purpose.

**Comment by plateaukao** [comment]
FYI
https://github.com/plateaukao/einkbro/commit/0b90e788a2823253bf316db3d2820bf90de3ff8d

**Comment by chwt163** [comment]
Sure enough, thank you!
