### ISSUE TITLE
[Feature Request] Is it possible to modify the UI to sandwich mode?

### ISSUE THREAD

**Issue by winstonma** [plateaukao/einkbro#83]
Based on my use case (I store my article in pocket and open the article in einkbro, so I seldom type the URL bar). I personally prefer the sandwich mode Via browser provides because the bottom bar would not be so packed. I attached the screenshot below:

![Via Browser Sandwich UI](https://1.bp.blogspot.com/-nXp1tn3dGws/WTSVVquD7mI/AAAAAAAFYig/Aeq9ugGCZR0UvvJ2lSz0ouff61MMSBCQACEw/s400/Via%2B%25E7%2580%258F%25E8%25A6%25BD%25E5%2599%25A8-01.png)

I would love to see this in einkbro. =)

**Comment by plateaukao** [comment]
@winstonma 

what do you mean by sandwich mode? does it mean there's even space between each icon across the whole toolbar? If so, I think you can try to build a version that adding all image buttons with layout_weight=1 inside the toolbar LinearLayout container. 

Since this is not a generic feature, I may not add it as an option in the release version.

**Comment by winstonma** [comment]
The [Via Browser](https://play.google.com/store/apps/details?id=mark.via.gp) provides three different location that you can put your toolbar

- Top
- Bottom
- Sandwich, this mode would split the toolbar into two toolbars. The top toolbar is the URL bar which I don't access at all. And they put all the button at the bottom toolbar. This config provides more space between buttons (or more buttons can be placed), also the page title would be visible to the user. I guess the reason they call it sandwich mode is because the web content is sandwiched by the toolbars =). This config make sense to me because all the action buttons are located at the bottom and the view (including URL bar) are located above. I added the annotation below:
![https __1 bp blogspot com_-nXp1tn3dGws_WTSVVquD7mI-mh](https://user-images.githubusercontent.com/1215090/154877076-02727554-df65-420a-ae2b-b839866065e8.png)

It may just make sense to me. Let's see if you agree on this.

**Comment by plateaukao** [comment]
@winstonma 

Now I know what it means now. In menu, there's a button for configure toolbar icons; in the toolbar configuration, **you can uncheck title, and add the input icon** (with a pen in the icon), it's only a button comparing to the long title strings. This may be helpful for your scenario, what do you think?

As for only putting title in top bar, I will consider it in the future, but it's not what I would work on soon. Because in order to do so, I also need to consider options for show/hide the top bar too. And... for me, I think it's always easier to just look at the web content directly instead of checkin the title to know what I am reading now.

**Comment by winstonma** [comment]
Thanks. Understand this is not the highest priority at all. Please take your time.

I tried the pen option and I think it is great too. I would expect that the buttons are spaced evenly instead of right align, when the title is disabled. But this is just my personal preference.

**Comment by plateaukao** [comment]
@winstonma About equal space between all icons, I could make it an option in settings (since it won't take too much time to implement and won't impact other users if they don't change it). I'll add it later and let you know when it's done. :)

**Comment by winstonma** [comment]
Thanks just take your time. It's a feature request and spacing buttons are a very low priority thing. It's just a nice to have thing.

Just learn that my annotation on the picture above was wrong =P

**Comment by plateaukao** [comment]
no intention to implement sandwich style of toolbar for now, so close the ticket.
